### ISSUE TITLE
Following the readme ends with an error

### ISSUE THREAD

**Issue by borgr** [sashgorokhov/python-telegram-handler#13]
I run the code you suggest to find the chat ID and got this error... What is wrong?

```
$ python3 -m telegram_handler 121231234:AAAaaaa_sdafdsa;'lkfd;'slakfd;l'sakfds

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/telegram_handler/__main__.py", line 4, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/telegram_handler/__init__.py", line 15, in main
    chat_id = handler.get_chat_id()
  File "/usr/local/lib/python3.5/dist-packages/telegram_handler/handlers.py", line 35, in get_chat_id
    if not response.get('ok', False):
AttributeError: 'Response' object has no attribute 'get'
```

**Comment by sashgorokhov** [comment]
Will fix that as part of #14
