### ISSUE TITLE
Initiating sometimes throws exception

### ISSUE THREAD

**Issue by borgr** [sashgorokhov/python-telegram-handler#14]
It doesn't happen always and retrying works, but it is an unexpected behaviour...

```python
Traceback (most recent call last):
File "/home/borgr/brandcoga/log_utils.py", line 29, in <module>
    telegram_handler = TelegramHandler(TELEGRAM_TOKEN)
  File "/usr/local/lib/python3.5/dist-packages/telegram_handler/handlers.py", line 21, in __init__
    self.chat_id = chat_id or self.get_chat_id()
  File "/usr/local/lib/python3.5/dist-packages/telegram_handler/handlers.py", line 35, in get_chat_id
    if not response.get('ok', False):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by sashgorokhov** [comment]
Hi! Thanks for your interest in my package. 

Could you please setup logging before creating TelegramHandler instance? I mean, configure logger named `telegram_handler`, with level DEBUG and StreamingHandler. There is an http error happens which is logged by internal logger which is disabled by default (line https://github.com/sashgorokhov/python-telegram-handler/blob/master/telegram_handler/handlers.py#L55). 

Looking forward for your results.

**Comment by borgr** [comment]
I ran it several times (I changed the DEBUG lines to be INFO internally, and initiated the root with DEBUG as I was not sure at the beginning the debugs are actually printed) \n\n\n is printed after every execution of the logging initialization.
Here is a working example, and two different not working examples
```

2018-09-10 12:36:31,538 INFO requests.packages.urllib3.connectionpool - Starting new HTTPS connection (1): api.telegram.org
2018-09-10 12:36:31,938 DEBUG requests.packages.urllib3.connectionpool - "POST /bot660295447:AAHxrzw_Vk5wcNkFE42aOl5OI-7SO2SIR50/getUpdates HTTP/1.1" 200 1250
2018-09-10 12:36:31,946 INFO telegram_handler.handlers - Chat id: 235317476
\n\n\n
2018-09-10 12:36:32,589 INFO requests.packages.urllib3.connectionpool - Starting new HTTPS connection (1): api.telegram.org
2018-09-10 12:36:34,906 ERROR telegram_handler.handlers - Error while making POST to https://api.telegram.org/bot660295447:AAHxrzw_Vk5wcNkFE42aOl5OI-7SO2SIR50/getUpdates
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram_handler/handlers.py", line 51, in request
    response = requests.post(url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=2)
2018-09-10 12:36:34,912 INFO telegram_handler.handlers - {'timeout': 2}
Traceback (most recent call last):
  File "log_utils.py", line 101, in <module>
    telegram_handler = TelegramHandler(TELEGRAM_TOKEN)
  File "/usr/local/lib/python3.5/dist-packages/telegram_handler/handlers.py", line 21, in __init__
    self.chat_id = chat_id or self.get_chat_id()
  File "/usr/local/lib/python3.5/dist-packages/telegram_handler/handlers.py", line 35, in get_chat_id
    if not response.get('ok', False):
AttributeError: 'NoneType' object has no attribute 'get'
\n\n\n
Traceback (most recent call last):
  File "log_utils.py", line 37, in <module>
    telegram_handler = TelegramHandler(TELEGRAM_TOKEN)
  File "/usr/local/lib/python3.5/dist-packages/telegram_handler/handlers.py", line 21, in __init__
    self.chat_id = chat_id or self.get_chat_id()
  File "/usr/local/lib/python3.5/dist-packages/telegram_handler/handlers.py", line 35, in get_chat_id
    if not response.get('ok', False):
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by sashgorokhov** [comment]
Looks like connectivity problem to me. Can you set the `timeout` parameter, to, lets say, 30, during the creation of TelegramHandler object?

**Comment by avi-av** [comment]
I met this problem when I ran 
`python -m $MYID TOKEN`
without apostrophe - " ' ".
